name: New Tool Submission
description: Submit a new AI tool for educators
title: "[NEW TOOL]: "
labels: ["new-content", "tool"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for submitting a new tool! Please fill out the information below.
  - type: input
    id: title
    attributes:
      label: Title
      description: The name of the tool
      placeholder: "AI Writing Assistant"
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A short description of the tool (1-2 sentences)
      placeholder: "This tool helps teachers provide writing feedback to students using AI."
    validations:
      required: true
  - type: input
    id: tags
    attributes:
      label: Tags
      description: Comma-separated list of tags (e.g., education,elementary,feedback)
      placeholder: "writing,feedback,assessment"
    validations:
      required: true
  - type: input
    id: github_link
    attributes:
      label: GitHub Repository
      description: Link to the tool's GitHub repository (if available)
      placeholder: "https://github.com/username/repository"
    validations:
      required: false
  - type: input
    id: filename
    attributes:
      label: Filename
      description: Kebab-case filename without extension (e.g., ai-writing-assistant)
      placeholder: "ai-writing-assistant"
    validations:
      required: true
  - type: textarea
    id: features
    attributes:
      label: Features
      description: List the key features of the tool
      placeholder: "- Feature 1\n- Feature 2\n- Feature 3"
    validations:
      required: true
  - type: textarea
    id: how_to_use
    attributes:
      label: How to Use
      description: Instructions on how to use the tool
      placeholder: "Explain how educators can use this tool in their classroom."
    validations:
      required: true